//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public Announcement()
        {
            this.Announcement_Characteristis = new HashSet<Announcement_Characteristis>();
            this.Responses = new HashSet<Responses>();
        }
    
        public int announcement_id { get; set; }
        public string photo { get; set; }
        public string title { get; set; }
        public Nullable<int> location { get; set; }
        public Nullable<int> characteristic_id { get; set; }
        public string description { get; set; }
        public Nullable<int> realtor_id { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Realtor Realtor { get; set; }
        public virtual ICollection<Announcement_Characteristis> Announcement_Characteristis { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual ICollection<Responses> Responses { get; set; }
    }
}
