//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement_Characteristis
    {
        public int announcement_characteristis_id { get; set; }
        public Nullable<int> announcement_id { get; set; }
        public Nullable<int> characteristic_id { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual Characteristics Characteristics { get; set; }
    }
}
