//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Responses = new HashSet<Responses>();
        }
    
        public int user_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> location { get; set; }
    
        public virtual Location Location1 { get; set; }
        public virtual ICollection<Responses> Responses { get; set; }
    }
}
